# This is a basic workflow to help you get started with Actions

name: Cypress End-To-End

# Controls when the action will run. 
on:     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-with-react-and-java:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./SportClub-ui/
          start: ./SportClub-ui/npm start, ./SportClub-api/mvn spring-boot:run
          wait-on: 'http://localhost:3000, http://localhost:8080'
