# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    paths:
      - 'SportClub-api/**'
      - '.github/**'
  pull_request:
    paths:
      - 'SportClub-api/**'
      - '.github/**'

defaults:
  run:
    working-directory: ./SportClub-api

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and Test with Maven
      run: mvn clean test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
