# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    paths:
      - 'SportClub-ui/**'
      - '.github/**'
  pull_request:
    paths:
      - 'SportClub-ui/**'
      - '.github/**'
    
defaults:
  run:
    working-directory: ./SportClub-ui
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install --no-optional
    - run: npm test



